### ISSUE TITLE
Maybe the source-code is wrong...

### ISSUE THREAD

**Issue by noctiomg** [vuejs-templates/simple-2.0#1]
The vue.js code from 'https://npmcdn.com/vue@next/dist/vue.js' can't support some feature of vue.
There will be something wrong if you use :

- {{{ domValue }}}
- v-for="(key,i) in data

Please correct it , thx~

**Comment by yyx990803** [comment]
- `{{{ }}}` is deprecated in 2.0.

- `v-for` now uses `(value, index)` and `(value, key, index)` syntax.

Please read https://github.com/vuejs/vue/issues/2873, thx~
